name: CI check
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv ruff pytest pytest-cov
          pipx install --force -e .
      
      - name: Run linter
        run: python -m ruff check gendiff
      
      - name: Generate coverage report
        run: |
          python -m pytest --cov=gendiff --cov-report xml --cov-report term tests/
          mv coverage.xml coverage-cobertura.xml
      
      - name: Upload to CodeClimate
        if: github.ref == 'refs/heads/main'
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: python -m pytest --cov=gendiff --cov-report xml tests/
          coverageLocations: ${{ github.workspace }}/coverage-cobertura.xml:coverage.py.xml
          debug: true