name: CI Pipeline
on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test] pytest-cov
      
      - name: Run tests with coverage
        run: |
          python -m pytest --cov=gendiff --cov-report=xml:coverage.xml --cov-report=term tests/
      
      - name: Verify coverage file
        run: |
          ls -la coverage.xml
          head -n 5 coverage.xml
          file coverage.xml
      
      - name: Upload to CodeClimate
        if: github.ref == 'refs/heads/main'
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{ github.workspace }}/coverage.xml:cobertura
          debug: true