name: CI Pipeline
on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage jq flake8
          pip install -e .[test]
      
      - name: Run linter
        run: |
          flake8 gendiff tests
      
      - name: Run tests with coverage
        run: |
          python -m pytest --cov=gendiff --cov-report=xml:coverage.xml --cov-report=term tests/
      
      - name: Install cc-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-reporter
          chmod +x ./cc-reporter
          ./cc-reporter --version
      
      - name: Prepare coverage for Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          # Инициализация репортера
          ./cc-reporter before-build
          # Форматирование отчета
          ./cc-reporter format-coverage coverage.xml -t coverage.py -o coverage.codeclimate.json
          # Суммирование покрытия
          ./cc-reporter sum-coverage coverage.codeclimate.json -o coverage.total.json -p 1
      
      - name: Upload to CodeClimate
        if: github.ref == 'refs/heads/main'
        uses: codeclimate/codeclimate-action@v1
        with:
          coverageCommand: ./cc-reporter upload-coverage -i coverage.total.json
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}