name: CI check
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv ruff  # Добавили ruff в основные зависимости
          make install
      
      - name: Run linter
        run: |
          python -m ruff check gendiff  # Прямой вызов через python -m
      
      - name: Run Tests
        run: |
          make test
      
      - name: Test & publish code coverage
        if: github.ref == 'refs/heads/main'
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          coverageCommand: make test-coverage
          debug: true