name: CI Pipeline
on: [push, pull_request]

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          pip install -e .[test]
      
      - name: Run tests with coverage
        run: |
          python -m pytest --cov=gendiff --cov-report=xml:coverage.xml --cov-report=term tests/
      
      - name: Download Code Climate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-reporter
          chmod +x ./cc-reporter
          ./cc-reporter --version
      
      - name: Prepare coverage data
        run: |
          # Initialize build
          ./cc-reporter before-build
          
          # Convert coverage.xml to Code Climate format
          ./cc-reporter format-coverage coverage.xml -t coverage.py -o coverage.codeclimate.json
          
          # Combine coverage reports (if needed)
          ./cc-reporter sum-coverage coverage.codeclimate.json -o coverage.total.json
      
      - name: Upload coverage to Code Climate
        if: github.ref == 'refs/heads/main'
        run: |
          ./cc-reporter upload-coverage -i coverage.total.json --debug